sudo: false

language: php

notifications:
  on_success: never
  on_failure: change

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0

cache:
  - composer
  - npm

before_script:
  - composer install
  - npm install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - grunt phpcs
  - phpunit
