sudo: false

language: php

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0

cache:
  directories:
    - vendor
    - node_modules

before_script:
  - composer install
  - npm install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - grunt phpcs
  - phpunit

branches:
  only:
    - master
